feature: Add ability to create StaticJsonRpcProvider with ConnectionInfo
blocknative/web3-onboard pull request #1031
Opened 2022-05-31 10:38 UTC by applicature-dlitvinov

### Description
Added ```providerConnectionInfo``` to the ```Chain``` model. It helps to create providers with authorization parameters.

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks

2022-05-31 10:57 UTC, applicature-dlitvinov commented
#1030 - related to an isuue.

2022-06-01 13:16 UTC, applicature-dlitvinov commented
@Adamj1232 @mahmud-bn @taylorjdawson please review PR.

2022-06-01 17:17 UTC, YugasVasyl approved these changes

2022-06-07 14:51 UTC, applicature-dlitvinov commented
@Adamj1232 Could you please review it?

2022-06-07 17:16 UTC, taylorjdawson commented
@applicature-dlitvinov Hey thanks for contributing! We'll take a look at this and get back to you 🙌

2022-06-07 23:47 UTC, taylorjdawson requested changes
Just a couple comments! Also could you provide an example of how you would use this? Thanks!

2022-06-07 23:47 UTC, taylorjdawson commented on .gitignore
> +/.idea
@applicature-dlitvinov Can you remove? thanks!

2022-06-07 23:47 UTC, taylorjdawson commented on packages/common/package.json
> +  "version": "2.1.1",
```suggestion
  "version": "2.1.1-alpha.1",
```

2022-06-08 09:19 UTC, applicature-dlitvinov commented
@taylorjdawson 
Sometimes we need to use a private network RPC URL with some credentials, It's more secure and more stable than native RPC (Sometimes has crashes or lags).

```
const onboard = Onboard({
      wallets: [injected],
      chains: [
        {
          id: '0x61',
          token: 'BNB',
          label: 'Binance Testnet',
          rpcUrl: `${CUCTOM_BSC_PRC}`,
          providerConnectionInfo: {
            url: `${CUCTOM_BSC_PRC}`,
            user: `${LOGIN}`,
            password: `${PASSWORD}`
          }
        },
        ...
      ]
    })
```

2022-06-08 09:24 UTC, applicature-dlitvinov commented
@taylorjdawson Coul. you please review again

2022-06-09 00:21 UTC, taylorjdawson approved these changes

2022-06-09 03:25 UTC, merged