[injected-wallets] : feat - add Exodus wallet
blocknative/web3-onboard pull request #1039
Opened 2022-06-04 10:50 UTC by bulgakovk

### Description

Adds support for Exodus Browser Extension

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks

2022-06-06 16:05 UTC, Adamj1232 commented on packages/injected/package.json
> +  "version": "2.1.0",
```suggestion
  "version": "2.0.8-alpha.1",
```

2022-06-09 18:53 UTC, bulgakovk commented
> @bulgakovk Hey! Could you update this PR with latest develop? Then we can get it merged in 👍🏾

Hey sure thing! Just rebased on the latest v2-develop branch

2022-06-09 22:02 UTC, taylorjdawson requested changes
Just version bump this and we're good!

2022-06-09 22:02 UTC, taylorjdawson commented on packages/injected/package.json
> +  "version": "2.0.8-alpha.1",
```suggestion
  "version": "2.0.9-alpha.1",
```

2022-06-10 21:27 UTC, taylorjdawson approved these changes

2022-06-10 21:28 UTC, merged