feat: intergration of Rabby wallet
blocknative/web3-onboard pull request #1069
Opened 2022-06-15 06:08 UTC by vvvvvv1vvvvvv

### Description
This PR add intergration of Rabby wallet, Rabby will add into the list if user installed Rabby

<img width="902" alt="image" src="https://user-images.githubusercontent.com/86296331/173754551-a145520a-8e8a-4934-803b-df151849f99e.png">

More about Rabby wallet: https://rabby.io/

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] This PR passes the Circle CI checks

2022-06-15 17:13 UTC, taylorjdawson requested changes
@vvvvvv1vvvvvv  A few comments but looks good, thanks for the contribution!

2022-06-15 17:13 UTC, taylorjdawson commented on packages/injected/package.json
> +  "version": "2.0.10",
```suggestion
  "version": "2.0.10-alpha.1",
```

2022-06-15 17:13 UTC, taylorjdawson commented on packages/injected/src/icons/rabby.ts
> +export default `<svg width="320" height="320" viewBox="0 0 320 320" fill="none" xmlns="http://www.w3.org/2000/svg">
@vvvvvv1vvvvvv We like to have the icons with 100% width and height, thanks!
```suggestion
export default `<svg width="100%" height="100%" viewBox="0 0 320 320" fill="none" xmlns="http://www.w3.org/2000/svg">
```

2022-06-15 17:13 UTC, taylorjdawson commented on packages/injected/src/types.ts
> +  Rabby = 'isRabby',
We have `trailingComma` disabled. I would run `yarn format` just to make sure your files are correctly formatted
```suggestion
  Rabby = 'isRabby'
```

2022-06-20 03:47 UTC, vvvvvv1vvvvvv commented
@taylorjdawson all suggestions fixed

2022-06-21 23:07 UTC, aaronbarnardsound commented
Thanks @vvvvvv1vvvvvv this looks good. We'll get this merged and released later this week.

2022-06-28 20:39 UTC, Adamj1232 commented on packages/injected/package.json
> +  "version": "2.0.11-alpha.2",
```suggestion
  "version": "2.0.12-alpha.1",
```

2022-06-28 20:40 UTC, Adamj1232 commented
@vvvvvv1vvvvvv we had a recent release so there is a conflict and a note to update the version otherwise I can get this merged as soon as this is completed

2022-06-29 14:37 UTC, Adamj1232 approved these changes
Nice, thank you for the PR!

2022-06-29 14:38 UTC, merged