Core: Add --onboard-wallet-app-icon-background and --onboard-modal-background
blocknative/web3-onboard pull request #1120
Opened 2022-07-01 15:01 UTC by ReflectiveChimp

### Description
- Add `--onboard-wallet-app-icon-background` to allow setting wallet icon background color.
- Add `--onboard-modal-background` to allow setting modal background color.

![image](https://user-images.githubusercontent.com/55021052/176918978-c93f437f-210f-45d1-9f62-d9df3e9abcd4.png)
`--onboard-modal-background` is needed to remove this white dotted line that appears if you change `--onboard-main-scroll-container-background` to something other than white.

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks

2022-07-01 17:45 UTC, Adamj1232 commented on packages/core/src/views/shared/WalletAppBadge.svelte
> +    background: var(--onboard-wallet-app-icon-background, var(--onboard-gray-500, var(--gray-500)));
```suggestion
    background: var(--onboard-wallet-app-icon-background-gray, var(--onboard-gray-500, var(--gray-500)));
```
We will want to make each more independent as far as the variable name is concerned. I think post-fixing the variable with the class color type can achieve this

2022-07-01 17:46 UTC, Adamj1232 requested changes
Hey @ReflectiveChimp! Thanks for the PR!
There was a release today so the base develop branch and version will need an update and a variable naming comment below

2022-07-02 18:52 UTC, ReflectiveChimp commented
@Adamj1232 No problem, updated!

I've bumped core version to 2.3.3 - let me now if you need changed.

2022-07-05 15:05 UTC, ReflectiveChimp commented on packages/core/package.json
> +  "version": "2.3.3",
Merged upstream and updated core version to 2.4.0-alpha.2

2022-07-05 15:12 UTC, Adamj1232 commented
> @Adamj1232 No problem, updated!
> 
> I've bumped core version to 2.3.3 - let me now if you need changed.

I just realized you are with Beefy. Been using your platform for a while now. Really appreciate your team and product. Your team was one of the main reasons I decided to work full time in the blockchain space. I have worked on a couple of projects with Terry and am in your discord server. If you need any support feel free to reach out. Ill get your requests in development ASAP

2022-07-05 15:14 UTC, Adamj1232 approved these changes

2022-07-05 15:15 UTC, merged