[core-v2.7.0-alpha.3, common-v2.1.8-alpha.1, hw-common-v1.0.0-alpha.1, demo-v2.0.8]: Feature -hw common
blocknative/web3-onboard pull request #1203
Opened 2022-08-08 23:14 UTC by mahmud-bn

### Description

This PR separates common packages into two packages. Also, get rids of node-builtins 

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] I have run `yarn type-check` & `yarn build` to confirm there are not any associated errors
- [ ] This PR passes the Circle CI checks

2022-08-09 16:04 UTC, Adamj1232 commented on packages/core/package.json
> +    "@web3-onboard/common": "^2.1.8-alpha.1",
```suggestion
    "@web3-onboard/common": "^2.2.0-alpha.1",
```

2022-08-09 16:04 UTC, Adamj1232 commented on .circleci/config.yml
> +  hwcommon:
```suggestion
  hw-common:
```

2022-08-09 16:04 UTC, Adamj1232 commented on .circleci/config.yml
> +  build-staging-hwcommon:
```suggestion
  build-staging-hw-common:
```

2022-08-09 16:05 UTC, Adamj1232 commented on .circleci/config.yml
> +  build-hwcommon:
```suggestion
  build-hw-common:
```
hyphen to follow naming convention

2022-08-09 16:07 UTC, Adamj1232 commented on packages/hw-common/package.json
> +  "version": "1.0.0-alpha.1",
```suggestion
  "version": "2.0.0-alpha.1",
```
Since we started all other packages at version 2 I think we can do the same here

2022-08-09 16:08 UTC, Adamj1232 commented on packages/hw-common/src/type.js
> +//# sourceMappingURL=type.js.map
Do we need this?

2022-08-09 16:09 UTC, Adamj1232 commented on packages/hw-common/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Shouldn't need this yarn.lock file within hw-common package

2022-08-09 16:09 UTC, Adamj1232 commented on packages/injected/package.json
> +    "@web3-onboard/common": "^2.1.8-alpha.1",
```suggestion
    "@web3-onboard/common": "^2.2.0-alpha.1",
```

2022-08-09 16:10 UTC, Adamj1232 commented on packages/ledger/package.json
> +    "@web3-onboard/common": "^2.1.8-alpha.1",
```suggestion
    "@web3-onboard/common": "^2.2.0-alpha.1",
```

2022-08-09 16:11 UTC, Adamj1232 requested changes
Looking good! A few comments but getting close!

2022-08-11 11:38 UTC, mahmud-bn commented on packages/hw-common/src/type.js
> +//# sourceMappingURL=type.js.map
No, please

2022-08-11 16:52 UTC, Adamj1232 commented on package.json
> +    "cipher-base": "^1.0.4",
Is this intended to be at the top level package.json?

2022-08-16 23:42 UTC, aaronbarnardsound commented
I have extended the scope of this PR. It now:

- Moves all hardware wallet related code from the `common` package to the `hw-common` package
- Fixes a validation bug for hardware wallets by extracting all common validation and putting it in the `common` package. This removes duplicate validation logic that was inconsistent
- Modifies build script to run serially so that it builds in order necessary for no errors
- Fixes type issues in the repo

2022-08-17 20:41 UTC, Adamj1232 commented on packages/vue/package.json
> +  "version": "2.1.7-alpha.1",
```suggestion
  "version": "2.2.0-alpha.1",
```
To keep aligned with minor bumps from these changes

2022-08-17 20:41 UTC, Adamj1232 commented on packages/react/package.json
> +  "version": "2.2.7-alpha.1",
```suggestion
  "version": "2.3.0-alpha.1",
```

2022-08-17 20:43 UTC, Adamj1232 approved these changes
Couple version changes for React & Vue packages to keep the pattern of minor bumps for packages with dep changes, `yarn.lock` changes look a little light as well...?
Other than that great work!

2022-08-17 23:23 UTC, merged