Update index.ts
blocknative/web3-onboard pull request #1272
Opened 2022-09-15 08:21 UTC by fuhuimin

### Description

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] I have run `yarn check` & `yarn build` to confirm there are not any associated errors
- [ ] This PR passes the Circle CI checks

2022-09-21 02:04 UTC, aaronbarnardsound requested changes
Just a small suggestion so that we can support all of the sign typed data method calls.

Could you also change the [version](/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/walletconnect/package.json#L3) to `2.1.3-alpha.1` as well.

2022-09-21 07:41 UTC, fuhuimin commented
thank you for your suggestion

2022-09-21 22:43 UTC, aaronbarnardsound commented
Looks good, but just need you to update the version :)

> Could you also change the [version](/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/walletconnect/package.json#L3) to `2.1.3-alpha.1` as well.

2022-09-22 03:25 UTC, fuhuimin commented
Sorry to bother you.
but i have a doubt for set the version to 2.1.3, because i found the last release version of @web3-onboard/walletconnect on [NPM](https://www.npmjs.com/package/@web3-onboard/walletconnect) is 2.1.2.
now i guess this repo we have the next version of onboard on branch v2-web3-onboard and is on version 2.1.3, so i have changed the version to 2.1.3-alpha.1.

2022-09-22 23:44 UTC, aaronbarnardsound approved these changes
Looks good!

2022-09-22 23:44 UTC, aaronbarnardsound commented
Fixes #1272

2022-09-22 23:45 UTC, merged