Added all platform support for injected Trust Wallet
blocknative/web3-onboard pull request #1357
Opened 2022-11-08 17:29 UTC by chaoticgoodpanda

…at there is a Trust Wallet browser extension.

### Description
I'm on the Trust team, and we have a Chrome browser extension released: https://chrome.google.com/webstore/detail/trust-wallet/egjidjbpglichdcondbcbdnbeeppgdph. Changing the platform param for Trust's injected wallet in Blocknative to be 'all' instead of 'mobile' so TW extension can be connected via blocknative-powered dApps.

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] I have run `yarn check` & `yarn build` to confirm there are not any associated errors
- [x] This PR passes the Circle CI checks

2022-11-09 18:14 UTC, Adamj1232 commented on packages/injected/package.json
> +    "@web3-onboard/core": "^2.10.0",
These can be removed from dependencies

2022-11-09 18:14 UTC, Adamj1232 commented on packages/injected/package.json
> +  "version": "2.3.1",
```suggestion
  "version": "2.3.1-alpha.1",
```
This will allow for alpha version publish for testing prior to production release

2022-11-09 18:17 UTC, Adamj1232 requested changes
Few changes and a comment for clarification requested

2022-11-10 15:26 UTC, chaoticgoodpanda commented on packages/injected/src/wallets.ts
> +  platforms: ['all']
Yes, that's it. Assumption is that's all that's needed to support our new browser extension: https://chrome.google.com/webstore/detail/trust-wallet/egjidjbpglichdcondbcbdnbeeppgdph

2022-11-10 15:26 UTC, chaoticgoodpanda commented on packages/injected/package.json
> +    "@web3-onboard/core": "^2.10.0",
Noted. Done.

2022-11-10 15:33 UTC, Adamj1232 commented on packages/injected/package.json
> +    "ethers": "^5.7.2",
```suggestion
```

2022-11-10 15:35 UTC, Adamj1232 commented on packages/injected/src/wallets.ts
> +  platforms: ['all']
@chaoticgoodpanda great, have you tested with the internal demo project(packages/demo) to verify W3O is working properly with changing of chains, signing, sending transaction, etc?

2023-01-13 16:41 UTC, Adamj1232 commented
Closing in favor of https://github.com/blocknative/web3-onboard/pull/1463

2023-01-13 16:41 UTC, closed without merging