upgrade coinbase wallet sdk
blocknative/web3-onboard pull request #1373
Opened 2022-11-20 21:46 UTC by cb-jake

### Description
upgrade coinbase wallet sdk v3.6.0

### Checklist
- [ ] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [ ] I tested locally to make sure this feature/fix works
- [ ] I have run `yarn check` & `yarn build` to confirm there are not any associated errors
- [ ] This PR passes the Circle CI checks

2022-11-21 19:02 UTC, Adamj1232 commented on packages/coinbase/yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
@cb-jake can you please remove this yarn.lock ad it is not required

2022-11-21 19:02 UTC, Adamj1232 commented on packages/coinbase/package.json
> +  "version": "2.2.0",
```suggestion
  "version": "2.2.0-alpha.1",
```
This will allow for publishing of an alpha package for testing

2022-11-21 19:03 UTC, Adamj1232 requested changes
@cb-jake thanks for the PR! a couple small comment. Can you also remove the packages/coinbase/yarn.lock file as its not required Thanks!

2022-11-21 19:58 UTC, cb-jake commented
Thanks @Adamj1232. I addressed your comments in [5615ce9](https://github.com/blocknative/web3-onboard/pull/1373/commits/5615ce911dd544ce5e0375bdf62916a718df28f9)

2022-11-28 23:47 UTC, Adamj1232 commented
@cb-jake we had a PR merged to fix the entry point for the coinbase SDK in certain envs. If you could please pull in the latest develop and push we can get this PR merged tomorrow. Thank you!

2022-11-30 16:58 UTC, cb-jake commented
Thanks @Adamj1232! I just rebased. LMK if anything else is needed!

2022-12-01 20:15 UTC, Adamj1232 commented on packages/coinbase/package.json
> +  "version": "2.2.1-alpha.1",
```suggestion
  "version": "2.2.0-alpha.1",
```

2022-12-01 20:16 UTC, Adamj1232 commented
> Thanks @Adamj1232! I just rebased. LMK if anything else is needed!

Great one small note on the PR. We will try and get an alpha version out this afternoon. Thanks again!

2022-12-01 21:59 UTC, Adamj1232 approved these changes
Thank you for this update, its much appreciated!!

2022-12-01 22:28 UTC, cb-jake commented
Thanks again @Adamj1232!

2022-12-01 22:31 UTC, merged