Feat/add SubWallet wallet
blocknative/web3-onboard pull request #1875
Opened 2023-08-10 04:30 UTC by S2kael

### Description

**Add SubWallet wallet into web3-onboard.**

SubWallet is the comprehensive non-custodial wallet solution for Polkadot, Substrate & Ethereum ecosystems. With the mission of bringing users closer to Web3, we envision a Web3 multiverse gateway through which users can enjoy multichain services with utmost ease and absolute security. Connecting and using blockchain-based applications is smoother than ever with SubWallet Browser Extension & SubWallet Mobile App.

The provider is available on window.SubWallet.

#### **_PLEASE NOTE- Checklist must be complete prior to review._**
### Checklist
- [x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x] Check the box that allows repo maintainers to update this PR
- [x] Test locally to make sure this feature/fix works
- [x] Run `yarn check-all` to confirm there are not any associated errors
- [x] Confirm this PR passes Circle CI checks
- [x] Add or update relevant information in the documentation

### Docs Checklist
- [x] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
- [x] Add/update the appropriate package README (if applicable)
- [x] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) (if applicable)
- [x] Add/update the related package in the `docs/package.json` file (if applicable)

### If this PR includes changes to add an injected wallet or SDK wallet module: 
Please complete the following using the internal demo package.
To run this demo use the command `yarn && yarn dev` to get the project running at `http://localhost:8080/`

#### Tests with demo app (injected)
- [x] send transaction
- [x] switch chains
- [x] sign message
- [x] sign typed message
- [x] disconnect

2023-08-10 21:38 UTC, taylorjdawson commented
@S2kael Thanks for this addition! Going to take a look at this PR and we'll get it merged  🙌

2023-08-11 23:29 UTC, taylorjdawson approved these changes

2023-08-11 23:32 UTC, taylorjdawson requested changes
We just want to bump the alpha version, but besides that it looks good 👍

2023-08-11 23:32 UTC, taylorjdawson commented on packages/demo/package.json
> +    "@web3-onboard/injected-wallets": "^2.10.6-alpha.1",
```suggestion
    "@web3-onboard/injected-wallets": "^2.10.5-alpha.2",
```

2023-08-11 23:32 UTC, taylorjdawson commented on packages/injected/package.json
> +  "version": "2.10.6-alpha.1",
```suggestion
  "version": "2.10.5-alpha.2",
```

2023-08-12 03:20 UTC, S2kael commented
> We just want to bump the alpha version, but besides that it looks good 👍
Thank you, i just think my pull request can be merge at the next version so i don't change the alpha version. But I updated my version

2023-08-12 22:55 UTC, taylorjdawson approved these changes

2023-08-12 22:56 UTC, merged