add  echooowallet
blocknative/web3-onboard pull request #2187
Opened 2024-05-06 06:01 UTC by rqzrqh

### Description

#### **_PLEASE NOTE- Checklist must be complete prior to review._**
### Checklist
- [x] Increment the version field in `package.json` of the package you have made changes in following [semantic versioning](https://semver.org/) and using alpha release tagging
- [x] Check the box that allows repo maintainers to update this PR
- [x] Test locally to make sure this feature/fix works
- [x] Run `yarn check-all` to confirm there are not any associated errors
- [x] Confirm this PR passes Circle CI checks
- [x] Add or update relevant information in the documentation

### Docs Checklist
- [x] Include a screenshot of any changes ([see docs README on running locally](https://github.com/blocknative/web3-onboard/blob/develop/docs/README.md))
- [x] Add/update the appropriate package README (if applicable)
- [x] Add/update the related module in the [docs demo](https://github.com/blocknative/web3-onboard/blob/develop/docs/src/lib/services/onboard.js) (if applicable)
- [x] Add/update the related package in the `docs/package.json` file (if applicable)

### If this PR includes changes to add an injected wallet or SDK wallet module: 
Please complete the following using the internal demo package.
To run this demo use the command `yarn && yarn dev` to get the project running at `http://localhost:8080/`

#### Tests with demo app (injected)
- [x] send transaction
- [x] switch chains
- [x] sign message
- [x] sign typed message
- [x] disconnect

#### Tests with demo app (SDK)
- [x] send transaction
- [x] switch chains
- [x] sign message
- [x] sign typed message
- [x] disconnect

2024-05-09 15:58 UTC, Adamj1232 requested changes
Hi @rqzrqh thank you for the PR to support echooo wallet. 
As this is an injected wallet we do not support adding a new module specific for the injected wallet as module upkeep is extensive and all actions of adding a whole new module for an injected wallet can be done through the injected-module package.
If you can remove the echoo package, echoo page within the docs and CI pipeline changes we should be gtg.

2024-05-14 09:33 UTC, lianshao123 commented
> 你好@rqzrqh感谢您的PR支持echooo钱包。 由于这是一个注入钱包，我们不支持添加特定于注入钱包的新模块，因为模块维护非常广泛，并且为注入钱包添加全新模块的所有操作都可以通过注入模块包完成。 如果你可以删除 echoo 包，文档中的 echoo 页面和 CI 管道更改我们应该是 gtg。

2024-05-14 16:17 UTC, lianshao123 commented
Is there any documentation that can help me complete the import of wallet plugin to blocknative? @Adamj1232

2024-05-14 16:19 UTC, Adamj1232 commented
@lianshao123 Steps to get this PR ready to go would be:

1. Remove packages/echooo
2. revert echooo package changes to .circleci/config.yml
3. remove the [...36]echooo/+page.md
4. remove web3-onboard/echo from docs/package.json & services/onboard.js

Here is some documentation around adding a wallet and contributing to the project - https://onboard.blocknative.com/docs/overview/contribution-guide#how-can-i-add-a-new-wallet-%F0%9F%92%B3

2024-05-17 01:40 UTC, lianshao123 commented
One version has been submitted, please review it @Adamj1232

2024-05-17 15:10 UTC, Adamj1232 commented on packages/demo/package.json
> +    "@web3-onboard/echooo": "2.0.1-alpha.1",
```suggestion
```

2024-05-17 16:53 UTC, Adamj1232 approved these changes
Looks good! Thank you for contributing to the project!

2024-05-17 20:43 UTC, merged