fix: update brave wallet identity check
blocknative/web3-onboard pull request #919
Opened 2022-04-05 22:04 UTC by josheleonard

### Description
Updates the identity check for Brave Wallet.

<img width="775" alt="Screen Shot 2022-04-05 at 4 04 28 PM" src="https://user-images.githubusercontent.com/30185185/161857477-edce04d5-2ae8-42bc-95c4-c03a732326ff.png">

### Checklist
- [X] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [X] The box that allows repo maintainers to update this PR is checked
- [X] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks

2022-04-06 00:46 UTC, aaronbarnardsound commented
Hey @josheleonard, thank you for this PR.

Do you happen to know if this change is backwards compatible with older versions of the Brave browser. My understanding is that the `isBraveWallet` flag was not previously attached to the Brave provider, so was wondering if this would break users on older versions?

2022-04-06 01:14 UTC, josheleonard commented
@aaronbarnardsound, with this change, versions of Brave without the isBraveWallet variable will fallback to showing connect with MetaMask.

2022-04-06 06:07 UTC, aaronbarnardsound requested changes
Just a couple of small changes and then I think we will be good to go.

2022-04-06 06:07 UTC, aaronbarnardsound commented on packages/demo/package.json
> +    "@web3-onboard/injected-wallets": "../injected",
```suggestion
    "@web3-onboard/injected-wallets": "^2.0.3",
```

2022-04-06 06:07 UTC, aaronbarnardsound commented on packages/injected/src/icons/brave.ts
> +<svg width="218px" height="256px" viewBox="0 0 218 256" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```suggestion
<svg height="100%" viewBox="0 0 218 256" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```
For all of our icons the largest dimension needs to be set to 100%, so in this case the height is larger, so we set that to 100% and then the width will scale automatically. This allows us to scale the icons for all of the UI.

2022-04-07 00:56 UTC, aaronbarnardsound approved these changes
Looks good

2022-04-07 00:57 UTC, merged

2022-04-07 02:52 UTC, aaronbarnardsound commented
@josheleonard In what cases is the `isBrave` flag added to the provider? I am on the latest version and the provider does not have that flag.

2022-04-07 17:16 UTC, josheleonard commented
@aaronbarnardsound, currently the `isBraveWallet` provider flag is only present in Beta builds. This flag will be present in release builds soon.